# Generated by Django 5.2.12 on 2026-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpsd',
            name='structure_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
