# Generated by Django 5.2.12 on 2026-03-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_mockupresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpsd',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpsd',
            name='psd_type',
            field=models.CharField(choices=[('preview', 'Preview'), ('mockup', 'Mockup')], default='preview', max_length=20),
        ),
    ]
