# Generated by Django 5.2.12 on 2026-03-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productpsd_name_productpsd_psd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpsd',
            name='image_without_warp',
            field=models.ImageField(blank=True, null=True, upload_to='psd_thumbnails/'),
        ),
    ]
